from modules import *

setheadercolor("teal")
clear()
printtotal("lime")
firstcommand("green", "purple")
topcmds(12,"green","magenta")
mostargs("cd", 5, "yellow")
mostargs("tree", 5, "red")
mostargs("python3", 12, "green")
percentage("python3","green")
percentage("cd","blue")
top_pings(5, "green")
hourly("green", "purple")
byweekday("purple", "blue")
hourchart("green", "purple")
daychart("green", "yellow")
pacman_pkgs("blue")
aur_pkgs("paru", "purple")
reset()
